### ISSUE TITLE
Snapshot is unavailable

### ISSUE THREAD

**Issue by blacky0x0** [testcontainers/testcontainers-spock#21]
Can't get a new snapshot from `jitpack.io`.
@kiview  How to circumvent the limitation? My project is hanged up while loading dependencies.

**Comment by kiview** [comment]
I would advise depending on a specific snapshot version. I'm also planning on providing a more stable dependency on Maven Central.

Did you try to depend on the most recent commit version?
```
	dependencies {
	        compile 'com.github.kiview:spock-docker-extension:684011c302'
	}
```

Maybe jitpack isn't able to build the project right know (because of jitpack problems).

At least this dependency should already be built by Jitpack and be available:
```
	dependencies {
	        compile 'com.github.kiview:spock-docker-extension:f1b42d14e4'
	}
```

**Comment by blacky0x0** [comment]
I've tried both solutions and both work fine. Many thanks for your answers. It was new to me.
By the way, it would be great to see this extension in maven repo.

**Comment by kiview** [comment]
You're definitely right, I've created the issue #22 to document, that this is a TODO.
